txt2img:
  prompts: "dog"
  sampler_name: k_euler_a
  ddim_steps: 20
  cfg_scale: 12.0
  n_iter: 1
  seed: ''
  base_size: 512
  max_size: 704
  sample_path: 'krita/output'

  normalize_prompt_weights: true
  use_gfpgan: false
  use_realesrgan: false
  realesrgan_model_name: RealESRGAN_x4plus_anime_6B
  ddim_eta: 0.0
  batch_size: 1
  variant_amount: 0.0
  variant_seed:

img2img:
  prompts: "dog"
  sampler_name: k_euler_a
  ddim_steps: 50
  cfg_scale: 12.0
  denoising_strength: 0.35
  n_iter: 1
  seed: ''
  base_size: 512
  max_size: 704
  sample_path: 'krita/output'

  normalize_prompt_weights: true
  use_gfpgan: false
  use_realesrgan: false
  realesrgan_model_name: RealESRGAN_x4plus_anime_6B
  batch_size: 1
  resize_mode: 'Just resize'

upscale:
  realesrgan_model_name: RealESRGAN_x4plus_anime_6B
  base_size: 512
  max_size: 1024
  sample_path: 'krita/output'

plugin:
  sample_path: 'krita/input'
